### ISSUE TITLE
You should contribute to the bit-preserve project.

### ISSUE THREAD

**Issue by qbancoffee** [Danjovic/MC-10#2]
I just saw your github repo on [CoCoTalk](https://youtu.be/qV-wpSs8uUc?t=7964) and this is something I was planning on
doing but since you've already done it, maybe you can contribute this design to the [Bit Preserve Project](https://www.baldengineer.com/bit-preserve-vintage-schematics-with-kicad.html)

The requirement being that you do it in KiCAD.

I've done this already for one of the Color Computer 2's and for the Color Computer 3. I even took a step further and made replacement PCB's and I think you could too.

[Main repository](https://github.com/baldengineer/bit-preserve)
[My fork of the repository](https://github.com/qbancoffee/bit-preserve)

Here are some videos I made for SepTandy where I make a CoCo 2.

[Video 1](https://youtu.be/H2KNHDKdDhw)
[Video 2](https://youtu.be/MNNGa4_IVk4)
[Video 3](https://youtu.be/sGEANZCR-Eo)
[Video 4](https://youtu.be/OPx7hGcEO9U)

The MC-10 is small enough to make a really cheap replacement PCB and it would be fun!

**Comment by Danjovic** [comment]
Your Coco2 rebuilt is amazing. 
I have just imported the schematics on Kicad and uploaded them. It have occurred to me to make a clone with some improvements but I never thought about doing a replacement board. At the moment I am working on a Video/Audio MOD board to replace the RF modulator.

**Comment by qbancoffee** [comment]
Thanks, it was fun making those boards!

Replacing the RF modulator sounds like a good thing to do. Are you thinking of making a composite video board?

**Comment by Danjovic** [comment]
Yes, a composite video (and audio) board is currently under development (https://hackaday.io/project/182433-mc-10-av-mod-board).

**Comment by Danjovic** [comment]
Composite AV board built ant tested, files uploaded to the project.

**Comment by qbancoffee** [comment]
Excellent! So you built and tested a board based on the design that is in this repo?
I see and AV composite board  design from 6 months ago, is this the one?

Thank you!

**Comment by Danjovic** [comment]
I have designed another A/V boad which should be easier to assemble because it uses header pins on the same places as the holes for the modulator shield to attach it to the MC-10 motherboard.
![board](https://user-images.githubusercontent.com/5844589/174056763-255b4d84-6d1b-4549-9994-6a7f6f6fb975.png)

**Comment by qbancoffee** [comment]
This is really nice. I think might try to make one of these.
