### ISSUE TITLE
Failed to open the Schematic for the AV MOD

### ISSUE THREAD

**Issue by SmakyTaky** [Danjovic/MC-10#3]
I tried to open the schematic for the AV mod or the PCB file (brd) on KiCad but I get an error message. Can you please include a project file to work with the schematic/board file? (Using KiCad 5.1.12)

Error shown saya it is unable to recognize these files.

EDIT: I managed to create the project by importing the eagle brd file into a new one. So that's solved.

**Comment by Danjovic** [comment]
thanks for the feedback. Closing the issue.
